name: Test

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches: [main, develop]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          cache: gradle
          distribution: zulu
          java-version: 17

      - name: Build
        run: |
          ./gradlew build --no-daemon

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          cache: gradle
          distribution: zulu
          java-version: 17

      - name: Test
        run: |
          ./gradlew test
